name: NS2 Simulation Runner

on: [push, pull_request]

jobs:
  run_ns2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install NS2
        run: |
          sudo apt update
          sudo apt install -y ns2 nam

      - name: Run NS2 Simulation
        run: ns simulation.tcl
